= Joshua Reynolds
:title: Joshua Reynolds - Curriculum Vitae
:description: The compelling tale of one human's journey from the beginning of a career to close to the moment you are reading. Enjoy!

_technical leadership_

With years of success building great digital products around the world, I lead with compassion and by example. I love shipping high quality code with the rest of the team and bring strategic thinking to steer us safely through the turbulent waters of the digital sea. My tools of choice are deep technical know-how, insatiable curiosity, data, empathy, dynamic communication, a growth mindset and a colorful terminal theme.

== currently offering
* Highly available software systems through robust architecture and design, agile footing, thoughtful crumple zones and the experienced application of modern software wisdom
* Powerful communication skills to build shared understanding between business and technical stakeholders and effectively connect with our customers and clients
* Staff development through establishing honest self-evaluation with feedback, learning, and coaching as a core norms
* A trusting environment where diversity and self-expression are encouraged and connection and common ground are celebrated
* Fun

== past experience

=== Software & Security Architect / People Manager <> _bettermarks, GmbH_
[cols="1,1", grid=none, frame=none, options="header"]
|===
|*Berlin, Germany & The Hague, The Netherlands*
>|_Jan 2022 - Jan 2024_
|===

I joined this adaptive math software company to practice broad impact work and improve the organization's capacity for self-awareness and learning by improving the effectiveness of our technical and social systems.  This meant identifying and establishing productive feedback loops in both software -- build systems, unit tests, development environments, observability measures -- and human systems -- Radical Candor, blameless postmortems, modeling feedback requests, and more. Shortly in to my tenure, I was internally recruited to guide Security Architecture and systematize security improvements throughout the organization's sociotechnical systems.

==== key accomplishments
Drove migration and adoption of cloud native design and implementation of our flagship product, ending years trapped in a bare metal data center enabling loosely coupled development and deployment of their services. +
`_Kubernetes, IONOS Cloud, Amazon Web Services (AWS), Postgresql, Mongo Atlas_`

Pioneered development of company-wide System Design Documentation System.  Instituted diagrams as code, arc42 architectural structure and version controlled Architectural Decision Records (ADRs) across company domains and teams. +
`_C4, Structurizr, Asciidoc, arc42, Kubernetes, AWS_`

Led data breach incident response, created mitigation strategies and spearheaded adoption of MFA and additional security policies across the organization. +
`_Entra ID (nee Azure Active Directory), Bitwarden, AWS_`

Led creation of AWS Organization and SSO design and led migration from haphazard legacy user accounts and permissions to clean & tested Infrastructure as Code (IaC) implementation approach. +
`_AWS Cloud Development Kit (CDK), TypeScript, AWS, AWS CloudFormation_`

Architected, designed and supported company flagship product and it's team resulting in an on-time and successful launch. +
`_React, single-spa, GraphQL, Python, Pyramid, PostgreSQL, Mongo Atlas, EventSourcing/CQRS_` 

Refactored and supported improvements to local developer environment stack. Implemented support for Apple M1 architecture based machines. +
`_Docker, Docker Compose, Kong Gateway, Bash, NGINX, Asciidoc_` 

Led adoption of consumer-driven testing for microservice testing across the organization allowing for more granular and flexible release cycles and dependency management. +
`_Pact, Python, TypeScript_` 

=== Principal DevOps Engineer <> _Untasked_
[cols="1,1", grid=none, frame=none, options="header"]
|===
|*Remote, USA*
>|_March 2020 - Dec 2021_
|===

I joined the productivity startup Untasked to establish the DevOps mindset, tool-set, and build out the practices that allowed us to ship high quality code early and often.

The work was **very** scrappy & hands-on.  I did whatever needed doing and filled any gaps that arose. My primary focus was on DevOps technical architecture and implementation with some full stack development thrown in when needed.

==== key accomplishments
Designed/Created all CI/CD architecture and pipelines reducing deployment and testing time to seconds/minutes. +
`_Google Cloud Platform (GCP), GitHub Actions, Kubernetes_`

Designed and integrated NLP pipeline for conversational task creation allowing for product experimentation. +
`_Python, Poetry, spaCy_`

Created Unit and System tests and designed test automation framework reducing regressions and increasing developer confidence.
`_Typescript, Jest, Cypress_`

Championed and led migration from JavaScript to TypeScript leading to improved code quality and reduced runtime errors / time spent debugging javascript bugs.

Designed and Deployed Helm based Kubernetes infrastructure and greatly simplified containerized deployment.
`GCP, Help, Kubernetes`

Architected, integrated and deployed to Google Cloud Platform and Terraform infrastructure components allowing for better management of system design and configuration.
`Terraform, GCP, GithubActions`

=== Principal Engineer <> _Reaktor, Inc_
[cols="1,1", grid=none, frame=none, options="header"]
|===
|*New York City, New York, USA*
>|_October 2016 - March 2020_
|===

I was recruited to this Finland-based digital strategy, design, and technology consultancy for my strong architectural and technical acumen, growth mindset, and superior communications skills to lead large-scale digital technology product development and project teams, spearhead internal development, and coach internal staff.

==== key accomplishments
Led the creation a web application/data pipeline product to aggregate and transform a daily 100M records of Nielson viewing data into an query optimized data store.  Reduced Viacom's sales team research request turnaround from up to 6 days to less than a minute. +
`_React, Typescript, Python, Pandas, GraphQL, Databricks_` 

Led a high-performance cross-functional team to create a novel hybrid application and build out a multichannel education platform. Managed the design of a supporting application development training module and trained and coached the client's teams on the methodology and approach. +
`_React, React Native, Node.js_` 

Built successful partnerships with NYU and the 3 NYC libraries to deliver Reaktor's Elements of AI to the public through a flipped classroom by including it as a key pillar of the NYU proposed Center for Responsible AI.

Coached team members to find innovative ways to approach and attain their workplace goals -- One developer coachee pursued his ambition into a sales role which lead to him winning a $250K contract for the business. +
`_Neuroleadership™ Brain Based Coaching_`

=== CTO | Cofounder <> _Bloopco, Inc._
[cols="1,1", grid=none, frame=none, options="header"]
|===
|*Los Angeles, California, USA*
>|_May 2015 - September 2016_
|===

My co-founder and I built this innovative health tech company from the ground up and successfully developed an app that leveraged biometrics to foster and encourage healthy behaviors through game play.

==== key accomplishments
Drove the entire go-to-market strategy, including prototyping the technology and product research and build-out. +
`_Bluetooth, Bluetooth Low Energy (BLE), Unity, C#_`

Developed and implemented a heart rate algorithm that detected stress reduction to identify the impact of stress reducing breathing techniques.

Designed and developed our signature game "The Way of the Bow" and created a swift animation library to extend limited iOS functionality. +
`watchOS, iOS, Swift`

Produced the first released app on the Apple Watch to use biometric data as game controls. +
`TestFlight, Apple Developer, Apple App Store`

=== Principal Consultant <> _The Electric Hand Ltd._
[cols="1,1", grid=none, frame=none, options="header"]
|===
|*New York City, New York, USA*
>|_August 2006 - May 2015_
|===

I led the start-up of this digital consultancy, serving the software and entertainment industries where I managed all daily operations within a highly competitive markets and drove product development, engineering, and video production.

==== key accomplishments
Hired, trained, and mentored a team of junior developers and grew technical skills to deliver significant upgrades on a challenging legacy product. +
`_Java, Scala, Play Framework, J2EE, Ant, Maven_` 

Edited the last 2 seasons of Futurama, earning recognition for editing excellence. +
`_Final Cut Pro, Adobe After Effects, Adobe Photoshop_` 

Drove a huge reduction in technical debt for a legacy Java/J2EE application, lowering licensing costs for the client $100K+ and implemented a modern continuous integration/continuous delivery pipeline to ensure stability and code quality. +
`_Java, Scala, Play Framework, J2EE, Ant, Maven_` 

Led full architecture and development of a Flask Application for microsubscriptions to support ad free journalism. +
`_Flask, Python, Stripe Payments API, PostgreSQL_` 

Designed and built a risk analysis foundation for project planning startup using Bayesian mathematics to help predict risk of software project failure. Startup later had a successful exit. +
`_Angular, Django, NumPy, pandas, Python_` 

== core skills 
[cols="1,1,1", grid=none, frame=none]
|===
a|* Software Development
* Software Architecture
* Test Driven Development
* eXtreme Programming
* Automated Testing
* Systems Thinking
* Cloud Computing

a|* Facilitation
* Recruiting
* Typescript
* Python
* Java
* Swift
* DevOps

a|* Kubernetes
* Data Science
* Decision-making
* Active Listening
* Agile Methodologies
* Product Development
* Coaching and Mentoring
* Nonviolent Communication
|===

== education
University of Minnesota, Minneapolis Bachelors Of Mathematics

== certifications 
* Certified LeSS Practitioner
* Neuroleadership Institute Certified Brain-Based Coach
* Certified VitalSmarts Crucial Conversations Trainer
* Certified Coastal Kayak Trip Leader

== personal details

location:: Den Haag, Nederland

hobbies:: 
* Avid Sea Kayaker in and around the New York Harbor - I circumnavigated Manhattan!
* Dedicated omafiets rider - I semicircumnavigated The Netherlands!
* Passionate Rust string processor - I circumnavigated a stack of slices!

== links
linkedIn:: https://www.linkedin.com/in/jshreynolds/
github:: https://github.com/jshreynolds
resumé:: https://github.com/jshreynolds/ceevee