name: "Curriculum Vitae Publisher"
on:
  push:
    branches:
      - main

jobs:
  generate_resume:
    name: Generate Resumé

    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: install poetry (in order to use caching strategy)
        run: |
          pipx install poetry

      - name: load python with poetry caching
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "poetry"

      - name: install poetry dependencies
        run: |
          poetry install
      
      - name: build the resumé
        run: |
          poetry run python publish_ceevee.py

      - name: extrapolate the version number
        run: echo "release_version=$(poetry version --short)" >> "$GITHUB_ENV"

      - name: store the cv
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: build/*.pdf
          if-no-files-found: error